//! Byte-compatible implementations of the Rails signing, encryption and serialization contracts
//! Campfire depends on. Every function here is verified against golden vectors generated by the
//! reference app (`vectors/rails_compat.json`, produced by `reference-tools/rails_compat_vectors.rb`),
//! and what it generates is checked by Rails itself (`reference-tools/rails_compat_verify_rust.rb`).
//!
//! The public signatures below are the interface other crates build against.

pub mod key_generator;
pub mod message_verifier;
pub mod message_encryptor;
pub mod cookies;
pub mod csrf;
pub mod signed_id;
pub mod global_id;
pub mod turbo;
pub mod password;

mod encoding;
mod json;
mod marshal;
mod metadata;

pub use key_generator::KeyGenerator;
pub use message_verifier::MessageVerifier;
pub use message_encryptor::MessageEncryptor;

/// Everything derived from `secret_key_base`, built once at boot and shared.
pub struct Secrets {
    pub key_generator: KeyGenerator,
}

impl Secrets {
    pub fn new(secret_key_base: &str) -> Self {
        Self { key_generator: KeyGenerator::new(secret_key_base) }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum Error {
    /// Malformed message or bad signature (Ruby's `:invalid_message_format`).
    #[error("invalid signature")]
    InvalidSignature,
    /// Authentic, but the payload doesn't deserialize (`:invalid_message_serialization`).
    #[error("invalid message")]
    InvalidMessage,
    #[error("expired")]
    Expired,
    /// Wrong purpose, or a purpose was expected and the message carries no metadata.
    #[error("purpose mismatch")]
    PurposeMismatch,
}

impl Error {
    /// `ActiveSupport::Messages::Rotator` only falls back to the next rotation on format and
    /// serialization errors. An expired or mismatched message stops at the first verifier.
    pub(crate) fn rotates(&self) -> bool {
        matches!(self, Error::InvalidSignature | Error::InvalidMessage)
    }
}

#[cfg(test)]
mod golden;
