//! Byte-compatible implementations of the Rails signing, encryption and serialization contracts
//! Campfire depends on. Every function here is verified against golden vectors generated by the
//! reference app (`vectors/*.json`, produced by `reference-tools/`).
//!
//! The public signatures below are the interface other crates build against. The owner of this
//! crate fills in the bodies; changing a signature requires updating its callers.

pub mod key_generator;
pub mod message_verifier;
pub mod message_encryptor;
pub mod cookies;
pub mod csrf;
pub mod signed_id;
pub mod global_id;
pub mod turbo;

pub use key_generator::KeyGenerator;
pub use message_verifier::MessageVerifier;
pub use message_encryptor::MessageEncryptor;

/// Everything derived from `secret_key_base`, built once at boot and shared.
pub struct Secrets {
    pub key_generator: KeyGenerator,
}

impl Secrets {
    pub fn new(secret_key_base: &str) -> Self {
        Self { key_generator: KeyGenerator::new(secret_key_base) }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid signature")]
    InvalidSignature,
    #[error("invalid message")]
    InvalidMessage,
    #[error("expired")]
    Expired,
    #[error("purpose mismatch")]
    PurposeMismatch,
}
